# Generated by Django 5.1.5 on 2025-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
