# Generated by Django 5.1.5 on 2025-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
